---
name: ip9
project_root: .
pre_window: source /opt/ros/jazzy/setup.zsh && source install/setup.zsh

windows:
  - editor:
      layout: main-horizontal
      panes:
        - nvim . 
        - 
           - export RCUTILS_COLORIZED_OUTPUT=1
           - colcon build --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
           - source install/setup.zsh
  - nodes:
      layout: tiled
      panes:
        - ../planner.sh
        - rqt
        - ros2 run tf2_ros static_transform_publisher 0 0 0 0 0 0 map base_link

