float32 find_person_probability
float32 drive_time_std
float32 robot_speed
float32 robot_accompany_speed
float32 conversation_probability
float32 conversation_duration_std
float32 time_buffer
bool enable_logging
string appointments_path
---
bool success
string message
