# Movement
float32 drive_time_std
float32 robot_speed
float32 robot_accompany_speed

# meeting
float32 find_person_probability
float32 conversation_probability
float32 conversation_duration_std
float32 conversation_duration_mean
float32 time_buffer

# Energy management
float32 energy_consumption_drive
float32 energy_consumption_base
float32 battery_capacity
float32 charging_rate
float32 low_battery_threshold

# General
float32[3] dock_pose
string appointments_path
bool cache_enabled
